# Generated by Django 3.0 on 2020-07-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200716_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_write',
            new_name='c_writer',
        ),
    ]
